---
- name: Install and manage Nginx on Ubuntu
  hosts: WebServerA1
  become: true
  gather_facts: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      notify: Restart Nginx  # Notificar al handler para reiniciar el servicio

    - name: Ensure Nginx is enabled to start at boot
      service:
        name: nginx
        enabled: yes

    - name: Check status of Nginx service
      service_facts:

    - name: Display Nginx service status
      debug:
        var: ansible_facts.services['nginx.service']  # Muestra el estado del servicio

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted  # Reiniciar el servicio si fue notificado
