---
- name: Install and manage Nginx on Ubuntu
  hosts: WebServerA1
  become: true
  gather_facts: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure Nginx is enabled to start at boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
