---
- name: Playbook para instalar y configurar Nginx en WebServerA1
  hosts: WebServerA1
  become: true
  tasks:

    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Actualizar todos los paquetes instalados
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Habilitar y asegurar que Nginx está en ejecución
      systemd:
        name: nginx.service
        enabled: true
        state: started
