---
- name: Playbook para instalar y configurar Nginx en webservera1
  hosts: webservera1
  become: true
  tasks:

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Actualizar todos los paquetes instalados
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Habilitar y asegurar que Nginx está en ejecución
      systemd:
        name: nginx
        enabled: true
        state: started

    - name: Permitir tráfico HTTP en el firewall
      ufw:
        rule: allow
        name: 'Nginx HTTP'

    - name: Permitir tráfico HTTPS en el firewall (opcional, si necesitas HTTPS)
      ufw:
        rule: allow
        name: 'Nginx HTTPS'

    - name: Verificar que Nginx está activo
      command: systemctl status nginx
      register: nginx_status
      ignore_errors: yes

    - name: Mostrar el estado de Nginx
      debug:
        var: nginx_status.stdout_lines
