---
- name: Actualizar sistemas Ubuntu
  hosts: "{{ target | default('all') }}"  # Por defecto, actualiza todos los hosts a menos que se especifique un objetivo
  become: true
  gather_facts: yes

  tasks:
    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes
      tags: update_cache

    - name: Actualizar todos los paquetes instalados
      apt:
        upgrade: dist
      tags: upgrade_all

    - name: Limpiar paquetes obsoletos
      apt:
        autoremove: yes
        purge: yes
      tags: cleanup
