---
- name: Update Operating System
  hosts: host_machine  # Cambiado de localhost a host_machine
  become: true
  gather_facts: no  # Desactiva la recolección de facts del sistema

  tasks:
    # Actualizar la lista de paquetes
    - name: Update package list
      apt:
        update_cache: yes
      tags: update

    # Actualizar todos los paquetes instalados
    - name: Upgrade all packages
      apt:
        upgrade: dist
      tags: upgrade
