---
- name: Actualizar servidores Ubuntu
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Verificar usuario actual
      command: whoami
      register: result
    - debug:
        var: result.stdout

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 86400
