---
- name: Update Operating System
  hosts: host_machine
  become: true
  gather_facts: no

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      tags: update

    - name: Upgrade all packages
      apt:
        upgrade: dist
      tags: upgrade
