---
- name: Actualizar servidores Ubuntu
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: configurar el intérpreter de python
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
  
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Actualizar paquetes instalados
      apt:
        upgrade: dist

    - name: Eliminar paquetes no utilizados
      apt:
        autoremove: yes
        autoclean: yes
