---
- name: Actualizar servidores Ubuntu
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 86400  # 1 día en segundos

    - name: Actualizar paquetes instalados
      apt:
        upgrade: dist

    - name: Eliminar paquetes no utilizados
      apt:
        autoremove: yes
        autoclean: yes
