---
- name: Configure PostgreSQL 14 and install Zabbix on Rocky Linux
  hosts: Zabbix
  become: true

  vars:
    admin_user: "admin"
    admin_user_password: "asd.1234"
    zabbix_db_user: "zabbix"
    zabbix_db_password: "asd.1234"
    zabbix_db_name: "zabbix"
    postgres_admin_password: "asd.1234"

  tasks:
  - name: Install PostgreSQL 14 and required packages
    dnf:
      name: 
        - https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        - postgresql14-server
    tags: install

  - name: Initialize PostgreSQL 14 database
    command: /usr/pgsql-14/bin/postgresql-14-setup initdb
    args:
      creates: /var/lib/pgsql/14/data/PG_VERSION
    tags: init_db

  - name: Start and enable PostgreSQL 14 service
    service:
      name: postgresql-14
      state: started
      enabled: yes
    tags: service

  - name: Set PostgreSQL superuser password
    become_user: postgres
    community.postgresql.postgresql_user:
      name: postgres
      password: "{{ postgres_admin_password }}"
      state: present
    tags: config

  - name: Create PostgreSQL admin user for routine tasks
    become_user: postgres
    community.postgresql.postgresql_user:
      name: "{{ admin_user }}"
      password: "{{ admin_user_password }}"
      role_attr_flags: CREATEDB,NOSUPERUSER
      state: present
    tags: users

  - name: Create Zabbix database
    become_user: postgres
    community.postgresql.postgresql_db:
      name: "{{ zabbix_db_name }}"
      encoding: "UTF8"
    tags: zabbix

  - name: Create Zabbix database user
    become_user: postgres
    community.postgresql.postgresql_user:
      name: "{{ zabbix_db_user }}"
      password: "{{ zabbix_db_password }}"
      priv: "{{ zabbix_db_name }}:ALL"
      state: present
    tags: zabbix

  - name: Grant privileges to Zabbix user on Zabbix database
    become_user: postgres
    community.postgresql.postgresql_privs:
      db: "{{ zabbix_db_name }}"
      roles: "{{ zabbix_db_user }}"
      objs: public
      type: schema
      privs: "ALL"
    tags: zabbix

  - name: Install Zabbix repository
    dnf:
      name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-3.el9.noarch.rpm
      state: present
    tags: install

  - name: Install Zabbix server, frontend, and agent
    dnf:
      name: 
        - zabbix-server-pgsql
        - zabbix-web-pgsql
        - zabbix-agent
      state: present
    tags: install

  - name: Import Zabbix database schema
    become_user: postgres
    command: >
      psql -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -f /usr/share/zabbix-server-pgsql/schema.sql
    args:
      creates: /var/lib/pgsql/14/data/zabbix_schema_imported
    tags: zabbix

  - name: Import Zabbix images data
    become_user: postgres
    command: >
      psql -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -f /usr/share/zabbix-server-pgsql/images.sql
    args:
      creates: /var/lib/pgsql/14/data/zabbix_images_imported
    tags: zabbix

  - name: Import Zabbix data data
    become_user: postgres
    command: >
      psql -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -f /usr/share/zabbix-server-pgsql/data.sql
    args:
      creates: /var/lib/pgsql/14/data/zabbix_data_imported
    tags: zabbix

  - name: Configure Zabbix server to use PostgreSQL
    lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^#? DBPassword='
      line: "DBPassword={{ zabbix_db_password }}"
    tags: config

  - name: Start and enable Zabbix server and agent
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - zabbix-server
      - zabbix-agent
    tags: service

  - name: Configure Zabbix to use PostgreSQL as the database in zabbix.conf.php
    blockinfile:
      path: /etc/zabbix/web/zabbix.conf.php
      marker: "# {mark} ANSIBLE MANAGED BLOCK ZABBIX CONFIG"
      block: |
        <?php
        $DB['TYPE']     = 'POSTGRESQL';
        $DB['SERVER']   = '10.243.0.35';
        $DB['PORT']     = '5432';
        $DB['DATABASE'] = '{{ zabbix_db_name }}';
        $DB['USER']     = '{{ zabbix_db_user }}';
        $DB['PASSWORD'] = '{{ zabbix_db_password }}';
        $DB['SCHEMA']   = 'public';
        $ZBX_SERVER     = '127.0.0.1';
        $ZBX_SERVER_PORT= '10051';
        $ZBX_SERVER_NAME= '';
        $IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
    tags: config

  - name: Ensure nginx-server is reachable from Zabbix
    ansible.builtin.wait_for:
      host: "10.243.0.35"
      port: 80
      state: started
      timeout: 30
    tags: connectivity
